// Text configuration for the entire application
// All UI text can be customized here
export const TEXT_CONFIG = {
  // App name
  appName: 'EMS 1.0',
  appFullName: 'Enterprise Management System',

  // Navigation
  nav: {
    dashboard: 'Dashboard',
    products: 'Products',
    sales: 'Sales',
    customers: 'Customers',
    settings: 'Settings',
    logs: 'Log History',
  },

  // Dashboard
  dashboard: {
    title: 'Dashboard',
    stats: {
      totalRevenue: 'Total Revenue',
      totalCost: 'Total Cost',
      profit: 'Profit',
      totalCustomers: 'Total Customers',
      totalProducts: 'Total Products',
      totalOverpaid: 'Total Overpaid',
      totalUnderpaid: 'Total Underpaid',
      netBalance: 'Net Balance',
    },
    charts: {
      topProducts: 'Top Selling Products',
      salesTrend: 'Sales Trend',
      purchaseTrend: 'Purchase Trend',
      lowStock: 'Low Stock Alert',
      revenue: 'Revenue',
      cost: 'Cost',
    },
    tables: {
      topSellingProducts: 'Top Selling Products',
      lowStockAlert: 'Low Stock Alert',
      productName: 'Product Name',
      qtySold: 'Qty Sold',
      revenue: 'Revenue',
      salesCount: 'Sales Count',
      quantity: 'Quantity',
      price: 'Price',
    },
    filters: {
      startDate: 'Start Date',
      endDate: 'End Date',
      productType: 'Product Type',
      apply: 'Apply Filter',
      reset: 'Reset',
    },
  },

  // Products
  products: {
    title: 'Products',
    tabs: {
      allProducts: 'All Products',
      purchaseHistory: 'Purchase History',
    },
    addButton: 'Add Product',
    table: {
      id: 'ID',
      name: 'Product Name',
      qty: 'Quantity',
      originalPrice: 'Original Price',
      salePrice: 'Sale Price',
      unit: 'Unit',
      createdAt: 'Created At',
      actions: 'Actions',
    },
    modal: {
      addTitle: 'Add New Product',
      editTitle: 'Edit Product',
      name: 'Product Name',
      qty: 'Quantity',
      originalPrice: 'Original Price',
      salePrice: 'Sale Price',
      unit: 'Unit',
      submit: 'Submit',
      cancel: 'Cancel',
      addQty: 'Add Quantity',
      addQtyTitle: 'Add Quantity to Product',
      price: 'Purchase Price',
      notes: 'Notes',
      productLabel: 'Product',
      currentQty: 'Current Qty',
      description: 'Description',
      descriptionHelper: 'Leave empty to use default description',
      defaultDescriptionInitial: 'Initial stock',
      defaultDescriptionStock: 'Stock addition',
      qtyHelper: 'Min: 1 (integer)',
      invalidQuantity: 'Please enter a valid quantity (minimum 1, integer only)',
    },
    purchaseHistory: {
      title: 'Purchase History',
      table: {
        id: 'ID',
        productName: 'Product Name',
        quantity: 'Quantity',
        price: 'Unit Price',
        total: 'Total Amount',
        date: 'Date',
        notes: 'Notes',
      },
    },
    actions: {
      edit: 'Edit',
      delete: 'Delete',
      addQty: 'Add Qty',
    },
    messages: {
      addSuccess: 'Product added successfully',
      editSuccess: 'Product updated successfully',
      deleteSuccess: 'Product deleted successfully',
      addQtySuccess: 'Quantity added successfully',
      duplicateName: 'A product with this name already exists',
      deleteConfirm: 'Are you sure you want to delete this product?',
    },
  },

  // Sales
  sales: {
    title: 'Sales',
    newSaleButton: 'New Sale',
      table: {
      id: 'ID',
      customerName: 'Customer',
      totalAmount: 'Total Amount',
      paidAmount: 'Paid Amount',
      paymentStatus: 'Status',
      saleDate: 'Sale Date',
      itemCount: 'Items',
      actions: 'Actions',
      viewDetails: 'View Order Details',
      delete: 'Delete Sale',
    },
    details: {
      title: 'Order Details',
      customer: 'Customer',
      date: 'Sale Date',
      notes: 'Notes',
      items: 'Order Items',
      product: 'Product',
      quantity: 'Quantity',
      unitPrice: 'Unit Price',
      subtotal: 'Subtotal',
      total: 'Total Amount',
      paid: 'Paid Amount',
      overpaid: 'Overpaid Amount',
      underpaid: 'Underpaid Amount',
    },
    modal: {
      title: 'New Sale',
      selectProduct: 'Select Product',
      qty: 'Quantity',
      addItem: 'Add Item',
      productName: 'Product',
      subtotal: 'Subtotal',
      totalAmount: 'Total Amount',
      total: 'Total',
      customerName: 'Customer Name',
      selectCustomer: 'Select Customer',
      selectCustomerRequired: 'Select Customer *',
      normalCustomer: 'Normal Customer',
      registeredCustomer: 'Registered Customer',
      paidAmount: 'Paid Amount',
      submit: 'Complete Sale',
      cancel: 'Cancel',
      removeItem: 'Remove',
    },
    paymentStatus: {
      paid: 'Paid',
      overpaid: 'Overpaid',
      underpaid: 'Underpaid',
    },
    messages: {
      addSuccess: 'Sale completed successfully',
      deleteSuccess: 'Sale deleted successfully',
      outOfStock: 'Some items are out of stock',
      noItems: 'Please add at least one item',
      deleteConfirm: 'Are you sure you want to delete this sale?',
    },
  },

  // Customers
  customers: {
    title: 'Customers',
    addButton: 'Add Customer',
    table: {
      id: 'ID',
      name: 'Name',
      phone: 'Phone',
      email: 'Email',
      address: 'Address',
      overpaidAmount: 'Overpaid',
      underpaidAmount: 'Underpaid',
      createdAt: 'Registered',
      actions: 'Actions',
    },
    modal: {
      addTitle: 'Add New Customer',
      editTitle: 'Edit Customer',
      name: 'Customer Name',
      phone: 'Phone Number',
      email: 'Email Address',
      address: 'Address',
      submit: 'Submit',
      cancel: 'Cancel',
    },
    actions: {
      edit: 'Edit',
      delete: 'Delete',
      view: 'View',
    },
    messages: {
      addSuccess: 'Customer added successfully',
      editSuccess: 'Customer updated successfully',
      deleteSuccess: 'Customer deleted successfully',
      duplicateName: 'A customer with this name already exists',
      deleteConfirm: 'Are you sure you want to delete this customer?',
    },
  },

  // Settings
  settings: {
    title: 'Settings',
    tabs: {
      units: 'Unit Management',
      userManagement: 'User Management',
      textConfiguration: 'Text Configuration',
      appearance: 'Appearance',
    },
    units: {
      addButton: 'Add Unit',
      table: {
        id: 'ID',
        name: 'Unit Name',
        abbreviation: 'Abbreviation',
        actions: 'Actions',
      },
      modal: {
        addTitle: 'Add New Unit',
        editTitle: 'Edit Unit',
        name: 'Unit Name',
        abbreviation: 'Abbreviation',
        submit: 'Submit',
        cancel: 'Cancel',
      },
      messages: {
        addSuccess: 'Unit added successfully',
        editSuccess: 'Unit updated successfully',
        deleteSuccess: 'Unit deleted successfully',
        duplicateName: 'A unit with this name already exists',
        inUse: 'Cannot delete unit that is being used by products',
        deleteConfirm: 'Are you sure you want to delete this unit?',
      },
    },
    userManagement: {
      title: 'User Management',
      addButton: 'Add User',
      table: {
        id: 'ID',
        username: 'Username',
        fullName: 'Full Name',
        permissions: 'Permissions',
        status: 'Status',
        actions: 'Actions',
        active: 'Active',
        inactive: 'Inactive',
        createdAt: 'Created At',
      },
      modal: {
        addTitle: 'Add New User',
        editTitle: 'Edit User',
        username: 'Username',
        usernameHelper: 'Enter a unique username',
        password: 'Password',
        passwordHelper: 'Enter a secure password (min 6 characters)',
        passwordHelperEdit: 'Leave blank to keep current password',
        fullName: 'Full Name',
        fullNameHelper: 'Enter full name',
        permissions: 'Permissions',
        permissionsHelper: 'Select which pages this user can access',
        isActive: 'Active',
        isActiveHelper: 'Toggle to activate or deactivate user',
        isActiveAdminNote: 'Active (Default admin cannot be deactivated)',
        isActiveDevNote: 'Active (Developer account cannot be deactivated)',
        submit: 'Submit',
        cancel: 'Cancel',
        create: 'Create',
        update: 'Update',
        createSuccess: 'User created successfully',
        updateSuccess: 'User updated successfully',
        passwordRequired: 'Password is required for new users',
        fillRequiredFields: 'Please fill in all required fields',
        onlyAdminCanChangePassword: 'Only admin user can change admin password',
        onlyDevCanChangePassword: 'Only dev user can change developer password',
        developerProtected: 'Developer account (protected)',
        editTooltip: 'Edit',
      },
      permissions: {
        dashboard: 'Dashboard',
        products: 'Products',
        sales: 'Sales',
        customers: 'Customers',
        settings: 'Settings',
        'settings.units': 'Settings - Units',
        'settings.users': 'Settings - User Management',
        'settings.textConfig': 'Settings - Text Configuration',
        'settings.appearance': 'Settings - Appearance',
        logs: 'Log History',
      },
      messages: {
        addSuccess: 'User added successfully',
        editSuccess: 'User updated successfully',
        deleteSuccess: 'User deleted successfully',
        deleteConfirm: 'Are you sure you want to delete this user?',
        cannotDeleteSelf: 'Cannot delete your own account',
        cannotDeleteAdmin: 'Default admin user cannot be deleted',
        cannotDeleteDev: 'Developer account cannot be deleted',
        adminProtected: 'Admin user is protected',
        devProtected: 'Developer account is protected',
      },
    },
    textConfiguration: {
      title: 'Text Configuration',
      subtitle: 'Customize all text labels and messages used throughout the application. Changes will be saved to the database and applied system-wide.',
      saveButton: 'Save Changes',
      resetButton: 'Reset to Default',
      savingButton: 'Saving...',
      sections: {
        appInfo: 'Application Info',
        navigation: 'Navigation',
        dashboard: 'Dashboard',
        products: 'Products',
        sales: 'Sales',
        customers: 'Customers',
        settings: 'Settings',
        auth: 'Authentication',
        userManagement: 'User Management',
        textConfig: 'Text Configuration',
        appearance: 'Appearance',
        logs: 'Log History',
        common: 'Common Elements',
      },
      messages: {
        saveSuccess: 'Text configuration saved successfully! Changes will apply immediately.',
        saveFailed: 'Failed to save configuration',
        resetSuccess: 'Configuration reset! Reloading page...',
        resetFailed: 'Failed to reset configuration',
        loadError: 'Error loading text configuration',
      },
    },
    appearance: {
      title: 'Appearance & Styling',
      subtitle: 'Customize the look and feel of the application. Changes will be saved to the database and applied system-wide.',
      saveButton: 'Save Changes',
      resetButton: 'Reset to Default',
      savingButton: 'Saving...',
      sections: {
        typography: 'Typography Settings',
        colors: 'Color Scheme',
        layout: 'Layout & Spacing',
        preview: 'Preview',
      },
      typography: {
        fontFamily: 'Font Family',
        fontSize: 'Font Size (px)',
        inputFontFamily: 'Input Font Family',
        inputFontSize: 'Input Font Size (px)',
        headingFontFamily: 'Heading Font Family',
      },
      colors: {
        primaryColor: 'Primary Color',
        secondaryColor: 'Secondary Color',
        successColor: 'Success Color',
        errorColor: 'Error Color',
        warningColor: 'Warning Color',
        infoColor: 'Info Color',
        backgroundColor: 'Background Color',
      },
      layout: {
        borderRadius: 'Border Radius (px)',
      },
      messages: {
        saveSuccess: 'Appearance settings saved successfully! Changes will apply immediately.',
        saveFailed: 'Failed to save configuration',
        resetSuccess: 'Appearance reset! Reloading page...',
        resetFailed: 'Failed to reset configuration',
        loadError: 'Error loading appearance configuration',
      },
    },
  },

  // Authentication & User
  auth: {
    loginTitle: 'EMS Login',
    loginSubtitle: 'Sign in to access the Enterprise Management System',
    username: 'Username',
    password: 'Password',
    loginButton: 'Sign In',
    logout: 'Logout',
    defaultCredentials: 'Default Credentials',
    profile: 'Profile',
    role: 'Role',
    roles: {
      admin: 'ADMIN',
      manager: 'MANAGER',
      staff: 'STAFF',
    },
  },

  // User Management
  userManagement: {
    title: 'User Management',
    addButton: 'Add User',
    table: {
      id: 'ID',
      username: 'Username',
      fullName: 'Full Name',
      role: 'Role',
      status: 'Status',
      actions: 'Actions',
    },
    modal: {
      addTitle: 'Add New User',
      editTitle: 'Edit User',
      username: 'Username',
      password: 'Password',
      fullName: 'Full Name',
      role: 'Role',
      isActive: 'Is Active',
      submit: 'Submit',
      cancel: 'Cancel',
    },
    messages: {
      addSuccess: 'User added successfully',
      editSuccess: 'User updated successfully',
      deleteSuccess: 'User deleted successfully',
      deleteConfirm: 'Are you sure you want to delete this user?',
      cannotDeleteSelf: 'Cannot delete your own account',
    },
    status: {
      active: 'Active',
      inactive: 'Inactive',
    },
  },

  // Text Configuration
  textConfig: {
    title: 'Text Configuration',
    subtitle: 'Customize all text labels and messages used throughout the application',
    saveButton: 'Save Changes',
    resetButton: 'Reset to Default',
    sections: {
      appInfo: 'Application Info',
      navigation: 'Navigation',
      dashboard: 'Dashboard',
      products: 'Products',
      sales: 'Sales',
      customers: 'Customers',
      settings: 'Settings',
      common: 'Common',
    },
  },

  // Appearance Configuration
  appearanceConfig: {
    title: 'Appearance & Styling',
    subtitle: 'Customize fonts and colors',
    saveButton: 'Save Changes',
    savingButton: 'Saving...',
    resetButton: 'Reset to Default',
    saveSuccess: 'Appearance settings saved successfully!',
    resetSuccess: 'Appearance reset to defaults!',
    sections: {
      typography: 'Typography',
      colors: 'Colors',
      timezone: 'Timezone Settings',
      inputFields: 'Input Fields',
      preview: 'Live Preview',
    },
    typography: {
      title: 'Typography',
      subtitle: 'Customize fonts used throughout the application',
      bodyFont: 'Body Font Family',
      bodyFontHelper: 'Enter any font name installed on your system',
      bodySize: 'Body Font Size (px)',
      headingFont: 'Heading Font Family',
      headingFontHelper: 'Custom font for titles and headings',
      inputFont: 'Input Font Family',
      inputFontHelper: 'Font for text input fields',
      inputSize: 'Input Font Size (px)',
      borderRadius: 'Border Radius (px)',
      borderRadiusHelper: 'Roundness of corners (0 = square, 20 = very round)',
      commonFonts: 'Common fonts:',
    },
    timezone: {
      title: 'Timezone Settings',
      subtitle: 'Configure timezone offset for date and time display',
      label: 'Timezone Offset',
      helper: 'Select GMT offset (e.g., GMT+9)',
      currentTime: 'Current Time',
    },
    currency: {
      title: 'Currency Settings',
      subtitle: 'Configure currency symbol for all monetary values',
      label: 'Currency Symbol',
      helper: 'Enter currency symbol (e.g., $, €, ¥, CNY, USD)',
      positionLabel: 'Symbol Position',
      positionHelper: 'Choose where to display the currency symbol',
      positionBefore: 'Before (e.g., $100)',
      positionAfter: 'After (e.g., 100$)',
      preview: 'Preview',
    },
    inputFields: {
      subtitle: 'Customize the appearance of input fields',
    },
    colors: {
      subtitle: 'Customize the color scheme of your application',
      primary: 'Primary Color',
      primaryHelper: 'Main theme color',
      secondary: 'Secondary Color',
      secondaryHelper: 'Accent color',
      success: 'Success Color',
      successHelper: 'Success messages',
      error: 'Error Color',
      errorHelper: 'Error messages',
      warning: 'Warning Color',
      warningHelper: 'Warning alerts',
      info: 'Info Color',
      infoHelper: 'Info notifications',
      background: 'Background Color',
      backgroundHelper: 'Page background',
    },
    preview: {
      title: 'Live Preview',
    },
  },

  // Common
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    reset: 'Reset',
    submit: 'Submit',
    yes: 'Yes',
    no: 'No',
    actions: 'Actions',
    noData: 'No data available',
    rowsPerPage: 'Rows per page',
    of: 'of',
  },

  // Log History
  logs: {
    title: 'Log History',
    subtitle: 'View all database activity logs',
    filters: {
      title: 'Filters',
      username: 'Username',
      tableName: 'Table Name',
      action: 'Action',
      status: 'Status',
      apply: 'Apply Filters',
      reset: 'Reset Filters',
    },
    table: {
      id: 'ID',
      timestamp: 'Time',
      username: 'User',
      action: 'Action',
      tableName: 'Table',
      recordId: 'Record ID',
      status: 'Status',
      errorMessage: 'Error',
      actions: 'Actions',
    },
    actions: {
      create: 'CREATE',
      update: 'UPDATE',
      delete: 'DELETE',
    },
    status: {
      success: 'Success',
      failed: 'Failed',
    },
    clearButton: 'Clear Log History',
    clearDialog: {
      title: 'Clear Log History',
      message: 'Are you sure you want to clear all log history? This action cannot be undone.',
    },
    details: {
      title: 'Log Details',
      field: 'Field',
      value: 'Value',
      ipAddress: 'IP Address',
      errorMessage: 'Error Message',
      beforeChanges: 'Before Changes',
      afterChanges: 'After Changes',
      noDataChanges: 'No data changes recorded for this log entry.',
    },
    messages: {
      noLogs: 'No activity logs found',
      loadError: 'Error loading activity logs',
      clearSuccess: 'Log history cleared successfully',
      clearFailed: 'Failed to clear log history',
    },
  },
};

export default TEXT_CONFIG;
